# Data Preview

In [15]:
import pandas as pd

# Select state (use abbreviation, e.g., 'CA' for California)
state = "CA"  # Change this to the desired state abbreviation

# Establishing the results file path
results_path = f"/Users/lukebincarousky/Downloads/NPPES/NPPES_Data_Dissemination_April_2026_V2/V1 States/{state} NPPES Extract.csv"

df = pd.read_csv(results_path, low_memory=False)

In [16]:
df

,index,NPI,Employer Identification Number (EIN),Provider Organization Name (Legal Business Name),Provider Last Name (Legal Name),Provider First Name,Provider Middle Name,Provider Name Prefix Text,Provider Name Suffix Text,Provider Credential Text,...,Healthcare Provider Taxonomy Code_5,Provider License Number_5,Provider License Number State Code_5,Healthcare Provider Primary Taxonomy Switch_5,Is Sole Proprietor,Is Organization Subpart,Parent Organization LBN,Parent Organization TIN,Healthcare Provider Taxonomy Group_1,Certification Date
0,5,1023011178,<UNAVAIL>,COLLABRIA CARE,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,05/15/2025
1,73,1023011053,<UNAVAIL>,VINE DISCOUNT PHARMACY & MEDICAL SUPPLY,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,04/22/2025
2,98,1801899836,NaN,NaN,ZICHELLA,SARAH,L,MRS.,NaN,PA-C,...,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN
3,144,1467455410,NaN,NaN,STRATIGOPOULOS,GEORGE,JOHN,DR.,NaN,D.D.S.,...,NaN,NaN,NaN,NaN,X,NaN,NaN,NaN,NaN,NaN
4,185,1215930250,NaN,NaN,PAGE,KIMBERLY,ANN,NaN,NaN,M.D.,...,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,02/04/2021
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1145587,9494395,1679416903,NaN,NaN,HERRERA,MONICA,ELISA,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,Y,NaN,NaN,NaN,NaN,04/11/2026
1145588,9494406,1487597712,<UNAVAIL>,RESILIENT RESTORATION LLC,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,193200000X MULTI-SPECIALTY GROUP,04/11/2026
1145589,9494414,1568305894,NaN,NaN,WEILAND,KEIFER,NaN,NaN,NaN,DO,...,NaN,NaN,NaN,NaN,Y,NaN,NaN,NaN,NaN,04/11/2026
1145590,9494431,1639012966,NaN,NaN,MARTINEZ GARCIA,KELVIN,NaN,NaN,NaN,MD,...,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,04/11/2026
1145591,9494432,1548103872,NaN,NaN,PARKER,SEAN,NaN,NaN,NaN,MD,...,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,04/11/2026

In [17]:
# Establishing the results file path
results2_path = f"/Users/lukebincarousky/Downloads/NPPES/NPPES_Data_Dissemination_April_2026_V2/V2 States/{state} NPPES Extract.csv"

df_2 = pd.read_csv(results2_path, low_memory=False)

In [18]:
df_2

,NPI,Employer Identification Number (EIN),Provider Organization Name (Legal Business Name),Provider Last Name (Legal Name),Provider First Name,Provider Middle Name,Provider Name Prefix Text,Provider Name Suffix Text,Provider Credential Text,Provider First Line Business Mailing Address,...,Healthcare Provider Taxonomy Code_5,Provider License Number_5,Provider License Number State Code_5,Healthcare Provider Primary Taxonomy Switch_5,Is Sole Proprietor,Is Organization Subpart,Parent Organization LBN,Parent Organization TIN,Healthcare Provider Taxonomy Group_1,Certification Date
0,1023011178,<UNAVAIL>,COLLABRIA CARE,NaN,NaN,NaN,NaN,NaN,NaN,414 S JEFFERSON ST,...,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,05/15/2025
1,1023011053,<UNAVAIL>,VINE DISCOUNT PHARMACY & MEDICAL SUPPLY,NaN,NaN,NaN,NaN,NaN,NaN,1253 N VINE ST,...,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,04/22/2025
2,1801899836,NaN,NaN,ZICHELLA,SARAH,L,MRS.,NaN,PA-C,2801 K ST,...,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN
3,1467455410,NaN,NaN,STRATIGOPOULOS,GEORGE,JOHN,DR.,NaN,D.D.S.,4808 CLAIREMONT MESA BLVD,...,NaN,NaN,NaN,NaN,X,NaN,NaN,NaN,NaN,NaN
4,1215930250,NaN,NaN,PAGE,KIMBERLY,ANN,NaN,NaN,M.D.,1388 COURT ST STE H,...,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,02/04/2021
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1145587,1679416903,NaN,NaN,HERRERA,MONICA,ELISA,NaN,NaN,NaN,5511 MICHELLE CT,...,NaN,NaN,NaN,NaN,Y,NaN,NaN,NaN,NaN,04/11/2026
1145588,1487597712,<UNAVAIL>,RESILIENT RESTORATION LLC,NaN,NaN,NaN,NaN,NaN,NaN,3300 ARCTIC BLVD STE 201,...,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,193200000X MULTI-SPECIALTY GROUP,04/11/2026
1145589,1568305894,NaN,NaN,WEILAND,KEIFER,NaN,NaN,NaN,DO,1731 E 120TH ST,...,NaN,NaN,NaN,NaN,Y,NaN,NaN,NaN,NaN,04/11/2026
1145590,1639012966,NaN,NaN,MARTINEZ GARCIA,KELVIN,NaN,NaN,NaN,MD,39000 BOB HOPE DR,...,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,04/11/2026
1145591,1548103872,NaN,NaN,PARKER,SEAN,NaN,NaN,NaN,MD,14445 OLIVE VIEW DR,...,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,04/11/2026