# Data Preview

In [ ]:
import pandas as pd

# Select state and scope
state = "MA"  # (use abbreviation, e.g., 'CA' for California)
scope = "Dental"  # Options: "Full Data", "Dental"
format = "csv" # Options: "csv", "parquet"

# Establishing the results file path
if format == "csv":
    if scope == "Full Data":
        results_path = f"/Users/lukebincarousky/Downloads/NPPES/NPPES_Data_Dissemination_May_2026_V2/{scope}/{state} NPPES Extract.csv"
    else:
        results_path = f"/Users/lukebincarousky/Downloads/NPPES/NPPES_Data_Dissemination_May_2026_V2/{scope}/{state} NPPES Dental.csv"
if format == "parquet":
    print("Parquet format is currently only available for Dental scope. Defaulting to Dental scope.")
    results_path = f"/Users/lukebincarousky/Downloads/NPPES/NPPES/data/NPPES_Data_Dissemination_May_2026_V2/Dental/{state} NPPES Dental.parquet"

if format == "csv":
    df = pd.read_csv(results_path, low_memory=False)
elif format == "parquet":
    df = pd.read_parquet(results_path)

Parquet format is currently only available for Dental scope. Defaulting to Dental scope.

In [35]:
df

,NPI,Employer Identification Number (EIN),Provider Organization Name (Legal Business Name),Provider Last Name (Legal Name),Provider First Name,Provider Middle Name,Provider Name Prefix Text,Provider Name Suffix Text,Provider Credential Text,Provider First Line Business Mailing Address,...,Spec_3,Code_4,Grouping_4,Class_4,Spec_4,Code_5,Grouping_5,Class_5,Spec_5,Deactivation Date
0,1841293834,None,None,WELLS,KEVIN,None,DR.,None,D.M.D.,793 LYNNFIELD ST,...,None,None,None,None,None,None,None,None,None,NaN
1,1174526172,None,None,BOUTROS,MAHA,G,DR.,None,D.M.D.,50 ROLLINGWOOD LN,...,None,None,None,None,None,None,None,None,None,NaN
2,1073516068,None,None,CORBEN,STEVEN,A.,DR.,None,D.M.D.,301 NEWBURY ST,...,None,None,None,None,None,None,None,None,None,NaN
3,1265435028,None,None,ORDEN,ADAM,None,DR.,None,"DDS, MS",1330 BEACON ST,...,None,None,None,None,None,None,None,None,None,NaN
4,1558364521,None,None,LEEMAN,RAMONA,L.,DR.,None,DDS,1051 BEACON ST,...,None,None,None,None,None,None,None,None,None,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14425,1740871227,<UNAVAIL>,READING DENTAL ASSOCIATES PC,None,None,None,None,None,None,161 ASH ST STE B,...,General Practice Dentistry,1223P0106X,Dental Providers,Dentist,Oral and Maxillofacial Pathology Dentistry,1223P0221X,Dental Providers,Dentist,Pediatric Dentistry,NaN
14426,1619640380,None,None,YOUNG,TAPHAPHENE,None,None,None,DMD,217 SOUTH ST,...,Endodontics,1223G0001X,Dental Providers,Dentist,General Practice Dentistry,1223P0221X,Dental Providers,Dentist,Pediatric Dentistry,NaN
14427,1396415295,<UNAVAIL>,HD GROUP LLC,None,None,None,None,None,None,169 LINCOLN ST STE 101,...,Periodontics,1223P0700X,Dental Providers,Dentist,Prosthodontics,122300000X,Dental Providers,Dentist,Dentist,NaN
14428,1386424786,<UNAVAIL>,WOBURN DENTISTRY PC,None,None,None,None,None,None,474 MAIN ST,...,General Practice Dentistry,1223P0106X,Dental Providers,Dentist,Oral and Maxillofacial Pathology Dentistry,1223P0221X,Dental Providers,Dentist,Pediatric Dentistry,NaN
14429,1770347858,<UNAVAIL>,WORCESTER DENTAL ARTS PLLC,None,None,None,None,None,None,87 ELM ST STE 302,...,Periodontics,1223S0112X,Dental Providers,Dentist,Oral and Maxillofacial Surgery (Dentist),1223X0400X,Dental Providers,Dentist,Orthodontics and Dentofacial Orthopedics Denti...,NaN

# Develop Re-Order Columns

In [36]:
df.columns

Index(['NPI', 'Employer Identification Number (EIN)',
       'Provider Organization Name (Legal Business Name)',
       'Provider Last Name (Legal Name)', 'Provider First Name',
       'Provider Middle Name', 'Provider Name Prefix Text',
       'Provider Name Suffix Text', 'Provider Credential Text',
       'Provider First Line Business Mailing Address',
       'Provider Second Line Business Mailing Address',
       'Provider Business Mailing Address City Name',
       'Provider Business Mailing Address State Name',
       'Provider Business Mailing Address Postal Code',
       'Provider Business Mailing Address Country Code (If outside U.S.)',
       'Provider Business Mailing Address Telephone Number',
       'Provider Business Mailing Address Fax Number',
       'Provider First Line Business Practice Location Address',
       'Provider Second Line Business Practice Location Address',
       'Provider Business Practice Location Address City Name',
       'Provider Business Practice Location Address State Name',
       'Provider Business Practice Location Address Postal Code',
       'Provider Business Practice Location Address Country Code (If outside U.S.)',
       'Provider Business Practice Location Address Telephone Number',
       'Provider Business Practice Location Address Fax Number',
       'Provider Enumeration Date', 'Last Update Date', 'Provider Sex Code',
       'Authorized Official Last Name', 'Authorized Official First Name',
       'Authorized Official Middle Name',
       'Authorized Official Title or Position',
       'Authorized Official Telephone Number',
       'Healthcare Provider Taxonomy Code_1', 'Provider License Number_1',
       'Provider License Number State Code_1',
       'Healthcare Provider Primary Taxonomy Switch_1',
       'Healthcare Provider Taxonomy Code_2', 'Provider License Number_2',
       'Provider License Number State Code_2',
       'Healthcare Provider Primary Taxonomy Switch_2',
       'Healthcare Provider Taxonomy Code_3', 'Provider License Number_3',
       'Provider License Number State Code_3',
       'Healthcare Provider Primary Taxonomy Switch_3',
       'Healthcare Provider Taxonomy Code_4', 'Provider License Number_4',
       'Provider License Number State Code_4',
       'Healthcare Provider Primary Taxonomy Switch_4',
       'Healthcare Provider Taxonomy Code_5', 'Provider License Number_5',
       'Provider License Number State Code_5',
       'Healthcare Provider Primary Taxonomy Switch_5', 'Is Sole Proprietor',
       'Is Organization Subpart', 'Parent Organization LBN',
       'Parent Organization TIN', 'Healthcare Provider Taxonomy Group_1',
       'Certification Date', 'ZipCode', 'County', 'Code_1', 'Grouping_1',
       'Class_1', 'Spec_1', 'Code_2', 'Grouping_2', 'Class_2', 'Spec_2',
       'Code_3', 'Grouping_3', 'Class_3', 'Spec_3', 'Code_4', 'Grouping_4',
       'Class_4', 'Spec_4', 'Code_5', 'Grouping_5', 'Class_5', 'Spec_5',
       'Deactivation Date'],
      dtype='object')

In [37]:
len(df.columns)

82

In [38]:
new_cols = ['NPI', 'Provider Name Prefix Text', 'Provider First Name', 'Provider Middle Name', 
        'Provider Last Name (Legal Name)', 'Provider Name Suffix Text', 'Provider Credential Text',
        'Provider Sex Code', 'Provider Enumeration Date', 'Last Update Date', 
        'Certification Date', 'Deactivation Date',
        
        # Practice Address 
        'Provider First Line Business Practice Location Address',
        'Provider Second Line Business Practice Location Address',
        'Provider Business Practice Location Address City Name',
        'Provider Business Practice Location Address State Name',
        'Provider Business Practice Location Address Postal Code',
        'ZipCode',
        'County',
        'Provider Business Practice Location Address Country Code (If outside U.S.)',
        'Provider Business Practice Location Address Telephone Number',
        'Provider Business Practice Location Address Fax Number',

        # Specialty Information
        'Code_1', 'Grouping_1', 'Class_1', 'Spec_1', 
        'Code_2', 'Grouping_2', 'Class_2', 'Spec_2',
        'Code_3', 'Grouping_3', 'Class_3', 'Spec_3', 
        'Code_4', 'Grouping_4', 'Class_4', 'Spec_4', 
        'Code_5', 'Grouping_5', 'Class_5', 'Spec_5',

        # License Information
        'Healthcare Provider Taxonomy Group_1',
        'Healthcare Provider Taxonomy Code_1', 'Provider License Number_1',
        'Provider License Number State Code_1',
        'Healthcare Provider Primary Taxonomy Switch_1',
        'Healthcare Provider Taxonomy Code_2', 'Provider License Number_2',
        'Provider License Number State Code_2',
        'Healthcare Provider Primary Taxonomy Switch_2',
        'Healthcare Provider Taxonomy Code_3', 'Provider License Number_3',
        'Provider License Number State Code_3',
        'Healthcare Provider Primary Taxonomy Switch_3',
        'Healthcare Provider Taxonomy Code_4', 'Provider License Number_4',
        'Provider License Number State Code_4',
        'Healthcare Provider Primary Taxonomy Switch_4',
        'Healthcare Provider Taxonomy Code_5', 'Provider License Number_5',
        'Provider License Number State Code_5',
        'Healthcare Provider Primary Taxonomy Switch_5',

        # Business Information
        'Employer Identification Number (EIN)', 'Provider Organization Name (Legal Business Name)',
        'Authorized Official First Name', 'Authorized Official Middle Name', 'Authorized Official Last Name', 
        'Authorized Official Title or Position', 'Authorized Official Telephone Number', 
        'Is Sole Proprietor', 'Is Organization Subpart', 'Parent Organization LBN', 'Parent Organization TIN',

        # Business Address
        'Provider First Line Business Mailing Address',
        'Provider Second Line Business Mailing Address',
        'Provider Business Mailing Address City Name',
        'Provider Business Mailing Address State Name',
        'Provider Business Mailing Address Postal Code',
        'Provider Business Mailing Address Country Code (If outside U.S.)',
        'Provider Business Mailing Address Telephone Number',
        'Provider Business Mailing Address Fax Number']

In [39]:
len(new_cols)

82

In [40]:
df = df[new_cols]

In [41]:
df

,NPI,Provider Name Prefix Text,Provider First Name,Provider Middle Name,Provider Last Name (Legal Name),Provider Name Suffix Text,Provider Credential Text,Provider Sex Code,Provider Enumeration Date,Last Update Date,...,Parent Organization LBN,Parent Organization TIN,Provider First Line Business Mailing Address,Provider Second Line Business Mailing Address,Provider Business Mailing Address City Name,Provider Business Mailing Address State Name,Provider Business Mailing Address Postal Code,Provider Business Mailing Address Country Code (If outside U.S.),Provider Business Mailing Address Telephone Number,Provider Business Mailing Address Fax Number
0,1841293834,DR.,KEVIN,None,WELLS,None,D.M.D.,M,05/23/2005,07/08/2007,...,None,None,793 LYNNFIELD ST,None,LYNN,MA,01904,US,7.815993e+09,7.815993e+09
1,1174526172,DR.,MAHA,G,BOUTROS,None,D.M.D.,F,05/23/2005,07/08/2007,...,None,None,50 ROLLINGWOOD LN,None,CONCORD,MA,01742,US,9.783696e+09,9.782876e+09
2,1073516068,DR.,STEVEN,A.,CORBEN,None,D.M.D.,M,05/23/2005,07/08/2007,...,None,None,301 NEWBURY ST,None,DANVERS,MA,01923,US,9.787627e+09,NaN
3,1265435028,DR.,ADAM,None,ORDEN,None,"DDS, MS",M,05/24/2005,07/08/2007,...,None,None,1330 BEACON ST,STE 344,BROOKLINE,MA,02446,US,6.172777e+09,6.172329e+09
4,1558364521,DR.,RAMONA,L.,LEEMAN,None,DDS,F,05/24/2005,07/08/2007,...,None,None,1051 BEACON ST,STE 409,BROOKLINE,MA,02446,US,6.172770e+09,6.177397e+09
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14425,1740871227,None,None,None,None,None,None,None,01/28/2021,01/28/2021,...,None,None,161 ASH ST STE B,None,READING,MA,01867,US,7.819447e+09,NaN
14426,1619640380,None,TAPHAPHENE,None,YOUNG,None,DMD,F,07/28/2021,10/16/2023,...,None,None,217 SOUTH ST,None,HOLYOKE,MA,01040,US,4.133191e+09,NaN
14427,1396415295,None,None,None,None,None,None,None,09/14/2021,09/14/2021,...,None,None,169 LINCOLN ST STE 101,None,HINGHAM,MA,02043,US,7.817400e+09,7.817405e+09
14428,1386424786,None,None,None,None,None,None,None,10/03/2023,10/03/2023,...,None,None,474 MAIN ST,None,WOBURN,MA,01801,US,7.816044e+09,NaN
14429,1770347858,None,None,None,None,None,None,None,02/09/2024,02/09/2024,...,None,None,87 ELM ST STE 302,None,HOPKINTON,MA,01748,US,5.085898e+09,NaN

In [42]:
# Dropping columns
df = df.drop(columns=['ZipCode', 'Healthcare Provider Taxonomy Group_1', 
                      'Provider Business Practice Location Address Country Code (If outside U.S.)',
                      'Provider Business Mailing Address Country Code (If outside U.S.)',
                      'Healthcare Provider Taxonomy Code_1',
                      'Healthcare Provider Taxonomy Code_2',
                      'Healthcare Provider Taxonomy Code_3',
                      'Healthcare Provider Taxonomy Code_4',
                      'Healthcare Provider Taxonomy Code_5',
                      'Healthcare Provider Primary Taxonomy Switch_1',
                      'Healthcare Provider Primary Taxonomy Switch_2',
                      'Healthcare Provider Primary Taxonomy Switch_3',
                      'Healthcare Provider Primary Taxonomy Switch_4',
                      'Healthcare Provider Primary Taxonomy Switch_5'
                      ])

# Rename columns for clarity
df = df.rename(columns={'Provider Enumeration Date': 'Enumeration Date', 
                        'Provider First Line Business Practice Location Address': 'Practice Address',
                        'Provider Second Line Business Practice Location Address': 'Practice Address2',
                        'Provider Business Practice Location Address City Name': 'Practice Address City',
                        'Provider Business Practice Location Address State Name': 'Practice Address State',
                        'Provider Business Practice Location Address Postal Code': 'Practice Address ZipCode',
                        'County': 'Practice Address County',
                        'Provider Business Practice Location Address Telephone Number': 'Practice Address Telephone',
                        'Provider Business Practice Location Address Fax Number': 'Practice Address Fax',

                        'Provider First Line Business Mailing Address': 'Business Address',
                        'Provider Second Line Business Mailing Address': 'Business Address2',
                        'Provider Business Mailing Address City Name': 'Business Address City',
                        'Provider Business Mailing Address State Name': 'Business Address State',
                        'Provider Business Mailing Address Postal Code': 'Business Address ZipCode',
                        'Provider Business Mailing Address Telephone Number': 'Business Address Telephone',
                        'Provider Business Mailing Address Fax Number': 'Business Address Fax',

                        'Code_1': 'Specialty Code 1', 
                        'Grouping_1': 'Specialty Grouping 1', 
                        'Class_1': 'Specialty Class 1', 
                        'Spec_1': 'Specialty 1', 
                        'Code_2': 'Specialty Code 2', 
                        'Grouping_2': 'Specialty Grouping 2', 
                        'Class_2': 'Specialty Class 2', 
                        'Spec_2': 'Specialty 2',
                        'Code_3': 'Specialty Code 3', 
                        'Grouping_3': 'Specialty Grouping 3', 
                        'Class_3': 'Specialty Class 3', 
                        'Spec_3': 'Specialty 3', 
                        'Code_4': 'Specialty Code 4', 
                        'Grouping_4': 'Specialty Grouping 4', 
                        'Class_4': 'Specialty Class 4', 
                        'Spec_4': 'Specialty 4', 
                        'Code_5': 'Specialty Code 5', 
                        'Grouping_5': 'Specialty Grouping 5', 
                        'Class_5': 'Specialty Class 5', 
                        'Spec_5': 'Specialty 5',  

                        'Provider License Number_1': 'License Number 1',
                        'Provider License Number State Code_1': 'License State 1',
                        'Provider License Number_2': 'License Number 2',
                        'Provider License Number State Code_2': 'License State 2',
                        'Provider License Number_3': 'License Number 3',
                        'Provider License Number State Code_3': 'License State 3',
                        'Provider License Number_4': 'License Number 4',
                        'Provider License Number State Code_4': 'License State 4',
                        'Provider License Number_5': 'License Number 5',
                        'Provider License Number State Code_5': 'License State 5'
                        })

In [43]:
df

,NPI,Provider Name Prefix Text,Provider First Name,Provider Middle Name,Provider Last Name (Legal Name),Provider Name Suffix Text,Provider Credential Text,Provider Sex Code,Enumeration Date,Last Update Date,...,Is Organization Subpart,Parent Organization LBN,Parent Organization TIN,Business Address,Business Address2,Business Address City,Business Address State,Business Address ZipCode,Business Address Telephone,Business Address Fax
0,1841293834,DR.,KEVIN,None,WELLS,None,D.M.D.,M,05/23/2005,07/08/2007,...,None,None,None,793 LYNNFIELD ST,None,LYNN,MA,01904,7.815993e+09,7.815993e+09
1,1174526172,DR.,MAHA,G,BOUTROS,None,D.M.D.,F,05/23/2005,07/08/2007,...,None,None,None,50 ROLLINGWOOD LN,None,CONCORD,MA,01742,9.783696e+09,9.782876e+09
2,1073516068,DR.,STEVEN,A.,CORBEN,None,D.M.D.,M,05/23/2005,07/08/2007,...,None,None,None,301 NEWBURY ST,None,DANVERS,MA,01923,9.787627e+09,NaN
3,1265435028,DR.,ADAM,None,ORDEN,None,"DDS, MS",M,05/24/2005,07/08/2007,...,None,None,None,1330 BEACON ST,STE 344,BROOKLINE,MA,02446,6.172777e+09,6.172329e+09
4,1558364521,DR.,RAMONA,L.,LEEMAN,None,DDS,F,05/24/2005,07/08/2007,...,None,None,None,1051 BEACON ST,STE 409,BROOKLINE,MA,02446,6.172770e+09,6.177397e+09
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14425,1740871227,None,None,None,None,None,None,None,01/28/2021,01/28/2021,...,N,None,None,161 ASH ST STE B,None,READING,MA,01867,7.819447e+09,NaN
14426,1619640380,None,TAPHAPHENE,None,YOUNG,None,DMD,F,07/28/2021,10/16/2023,...,None,None,None,217 SOUTH ST,None,HOLYOKE,MA,01040,4.133191e+09,NaN
14427,1396415295,None,None,None,None,None,None,None,09/14/2021,09/14/2021,...,N,None,None,169 LINCOLN ST STE 101,None,HINGHAM,MA,02043,7.817400e+09,7.817405e+09
14428,1386424786,None,None,None,None,None,None,None,10/03/2023,10/03/2023,...,N,None,None,474 MAIN ST,None,WOBURN,MA,01801,7.816044e+09,NaN
14429,1770347858,None,None,None,None,None,None,None,02/09/2024,02/09/2024,...,N,None,None,87 ELM ST STE 302,None,HOPKINTON,MA,01748,5.085898e+09,NaN