# Data Preview

In [1]:
import pandas as pd

# Select state (use abbreviation, e.g., 'CA' for California)
state = "CA"  # Change this to the desired state abbreviation

# Establishing the results file path
results_path = f"/Users/lukebincarousky/Downloads/NPPES/NPPES_Data_Dissemination_May_2026_V2/States/{state} NPPES Extract.csv"

df = pd.read_csv(results_path, low_memory=False)

In [2]:
df

,NPI,Employer Identification Number (EIN),Provider Organization Name (Legal Business Name),Provider Last Name (Legal Name),Provider First Name,Provider Middle Name,Provider Name Prefix Text,Provider Name Suffix Text,Provider Credential Text,Provider First Line Business Mailing Address,...,Healthcare Provider Taxonomy Code_5,Provider License Number_5,Provider License Number State Code_5,Healthcare Provider Primary Taxonomy Switch_5,Is Sole Proprietor,Is Organization Subpart,Parent Organization LBN,Parent Organization TIN,Healthcare Provider Taxonomy Group_1,Certification Date
0,1023011178,<UNAVAIL>,COLLABRIA CARE,NaN,NaN,NaN,NaN,NaN,NaN,414 S JEFFERSON ST,...,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,05/15/2025
1,1023011053,<UNAVAIL>,VINE DISCOUNT PHARMACY & MEDICAL SUPPLY,NaN,NaN,NaN,NaN,NaN,NaN,1253 N VINE ST,...,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,04/22/2025
2,1801899836,NaN,NaN,ZICHELLA,SARAH,L,MRS.,NaN,PA-C,2801 K ST,...,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN
3,1467455410,NaN,NaN,STRATIGOPOULOS,GEORGE,JOHN,DR.,NaN,D.D.S.,4808 CLAIREMONT MESA BLVD,...,NaN,NaN,NaN,NaN,X,NaN,NaN,NaN,NaN,NaN
4,1215930250,NaN,NaN,PAGE,KIMBERLY,ANN,NaN,NaN,M.D.,1388 COURT ST STE H,...,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,02/04/2021
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1153137,1134057391,NaN,NaN,ARZETA,JENNIFER,NaN,NaN,NaN,NaN,1737 ATLANTA AVE STE H5,...,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,05/09/2026
1153138,1861320020,NaN,NaN,BIMANYWARUHANGA,BENJAMIN,NaN,NaN,NaN,NaN,1721 BROADWAY,...,NaN,NaN,NaN,NaN,Y,NaN,NaN,NaN,NaN,05/09/2026
1153139,1689502841,NaN,NaN,CALO,ROMMEL VINCENT,URUBIO,NaN,NaN,NaN,1700 COFFEE RD,...,NaN,NaN,NaN,NaN,Y,NaN,NaN,NaN,NaN,05/09/2026
1153140,1033047295,<UNAVAIL>,CARINGHANDS HAYWARD LLC,NaN,NaN,NaN,NaN,NaN,NaN,18905 STANDISH AVE,...,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,05/09/2026
1153141,1588592745,NaN,NaN,RODRIGUEZ,NANCY,NaN,NaN,NaN,RDHAP,310 E HOUSTON ST APT A,...,NaN,NaN,NaN,NaN,Y,NaN,NaN,NaN,NaN,05/09/2026

- Mapping Specialties to Taxonomy
- Cleaning City column
- ZipCode to 5 digits
- Adding County

In [3]:
df['Provider Business Mailing Address Postal Code'] = df['Provider Business Mailing Address Postal Code'].astype(str).str[:5]
df['Provider Business Practice Location Address Postal Code'] = df['Provider Business Practice Location Address Postal Code'].astype(str).str[:5]

In [4]:
df['Provider Business Mailing Address Telephone Number'] = df['Provider Business Mailing Address Telephone Number'].astype(str).str[:10]
df['Provider Business Mailing Address Fax Number'] = df['Provider Business Mailing Address Fax Number'].astype(str).str[:10]
df['Provider Business Practice Location Address Telephone Number'] = df['Provider Business Practice Location Address Telephone Number'].astype(str).str[:10]
df['Provider Business Practice Location Address Fax Number'] = df['Provider Business Practice Location Address Fax Number'].astype(str).str[:10]
df['Authorized Official Telephone Number'] = df['Authorized Official Telephone Number'].astype(str).str[:10]

In [5]:
df.iloc[0]

NPI                                                                                                  1023011178
Employer Identification Number (EIN)                                                                  <UNAVAIL>
Provider Organization Name (Legal Business Name)                                                 COLLABRIA CARE
Provider Last Name (Legal Name)                                                                             NaN
Provider First Name                                                                                         NaN
Provider Middle Name                                                                                        NaN
Provider Name Prefix Text                                                                                   NaN
Provider Name Suffix Text                                                                                   NaN
Provider Credential Text                                                                                    NaN
Provider First Line Business Mailing Address                                                 414 S JEFFERSON ST
Provider Second Line Business Mailing Address                                                               NaN
Provider Business Mailing Address City Name                                                                NAPA
Provider Business Mailing Address State Name                                                                 CA
Provider Business Mailing Address Postal Code                                                             94559
Provider Business Mailing Address Country Code (If outside U.S.)                                             US
Provider Business Mailing Address Telephone Number                                                   7072589080
Provider Business Mailing Address Fax Number                                                         7072582476
Provider First Line Business Practice Location Address                                       414 S JEFFERSON ST
Provider Second Line Business Practice Location Address                                                     NaN
Provider Business Practice Location Address City Name                                                      NAPA
Provider Business Practice Location Address State Name                                                       CA
Provider Business Practice Location Address Postal Code                                                   94559
Provider Business Practice Location Address Country Code (If outside U.S.)                                   US
Provider Business Practice Location Address Telephone Number                                         7072589080
Provider Business Practice Location Address Fax Number                                               7072582476
Provider Enumeration Date                                                                            05/23/2005
Last Update Date                                                                                     05/15/2025
Provider Sex Code                                                                                           NaN
Authorized Official Last Name                                                                          ANDERSON
Authorized Official First Name                                                                           DONALD
Authorized Official Middle Name                                                                           WAYNE
Authorized Official Title or Position                                         ASSISTANT SECRETARY OF ENROLLMENT
Authorized Official Telephone Number                                                                 4253589786
Healthcare Provider Taxonomy Code_1                                                                  251G00000X
Provider License Number_1                                                                             100000741
Provider License Number State Code_1                                                                         CA
Healthcare Provider Primary Taxonomy Switch_1                                                                 Y
Healthcare Provider Taxonomy Code_2                                                                         NaN
Provider License Number_2                                                                                   NaN
Provider License Number State Code_2                                                                        NaN
Healthcare Provider Primary Taxonomy Switch_2                                                               NaN
Healthcare Provider Taxonomy Code_3                                                                         NaN
Provider License Number_3                                                                                   NaN
Provider License Number State Code_3                                                                        NaN
Healthcare Provider Primary Taxonomy Switch_3                                                               NaN
Healthcare Provider Taxonomy Code_4                                                                         NaN
Provider License Number_4                                                                                   NaN
Provider License Number State Code_4                                                                        NaN
Healthcare Provider Primary Taxonomy Switch_4                                                               NaN
Healthcare Provider Taxonomy Code_5                                                                         NaN
Provider License Number_5                                                                                   NaN
Provider License Number State Code_5                                                                        NaN
Healthcare Provider Primary Taxonomy Switch_5                                                               NaN
Is Sole Proprietor                                                                                          NaN
Is Organization Subpart                                                                                       N
Parent Organization LBN                                                                                     NaN
Parent Organization TIN                                                                                     NaN
Healthcare Provider Taxonomy Group_1                                                                        NaN
Certification Date                                                                                   05/15/2025
Name: 0, dtype: object

In [6]:
df

,NPI,Employer Identification Number (EIN),Provider Organization Name (Legal Business Name),Provider Last Name (Legal Name),Provider First Name,Provider Middle Name,Provider Name Prefix Text,Provider Name Suffix Text,Provider Credential Text,Provider First Line Business Mailing Address,...,Healthcare Provider Taxonomy Code_5,Provider License Number_5,Provider License Number State Code_5,Healthcare Provider Primary Taxonomy Switch_5,Is Sole Proprietor,Is Organization Subpart,Parent Organization LBN,Parent Organization TIN,Healthcare Provider Taxonomy Group_1,Certification Date
0,1023011178,<UNAVAIL>,COLLABRIA CARE,NaN,NaN,NaN,NaN,NaN,NaN,414 S JEFFERSON ST,...,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,05/15/2025
1,1023011053,<UNAVAIL>,VINE DISCOUNT PHARMACY & MEDICAL SUPPLY,NaN,NaN,NaN,NaN,NaN,NaN,1253 N VINE ST,...,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,04/22/2025
2,1801899836,NaN,NaN,ZICHELLA,SARAH,L,MRS.,NaN,PA-C,2801 K ST,...,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN
3,1467455410,NaN,NaN,STRATIGOPOULOS,GEORGE,JOHN,DR.,NaN,D.D.S.,4808 CLAIREMONT MESA BLVD,...,NaN,NaN,NaN,NaN,X,NaN,NaN,NaN,NaN,NaN
4,1215930250,NaN,NaN,PAGE,KIMBERLY,ANN,NaN,NaN,M.D.,1388 COURT ST STE H,...,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,02/04/2021
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1153137,1134057391,NaN,NaN,ARZETA,JENNIFER,NaN,NaN,NaN,NaN,1737 ATLANTA AVE STE H5,...,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,05/09/2026
1153138,1861320020,NaN,NaN,BIMANYWARUHANGA,BENJAMIN,NaN,NaN,NaN,NaN,1721 BROADWAY,...,NaN,NaN,NaN,NaN,Y,NaN,NaN,NaN,NaN,05/09/2026
1153139,1689502841,NaN,NaN,CALO,ROMMEL VINCENT,URUBIO,NaN,NaN,NaN,1700 COFFEE RD,...,NaN,NaN,NaN,NaN,Y,NaN,NaN,NaN,NaN,05/09/2026
1153140,1033047295,<UNAVAIL>,CARINGHANDS HAYWARD LLC,NaN,NaN,NaN,NaN,NaN,NaN,18905 STANDISH AVE,...,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,05/09/2026
1153141,1588592745,NaN,NaN,RODRIGUEZ,NANCY,NaN,NaN,NaN,RDHAP,310 E HOUSTON ST APT A,...,NaN,NaN,NaN,NaN,Y,NaN,NaN,NaN,NaN,05/09/2026

In [7]:
'Provider Business Practice Location Address City Name'

'Provider Business Practice Location Address City Name'

In [8]:
'Healthcare Provider Taxonomy Code_1'

'Healthcare Provider Taxonomy Code_1'